# Generated by Django 3.0.2 on 2021-08-16 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20210816_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='暫無說明', verbose_name='說明'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nickname',
            field=models.CharField(default='超值二手機', max_length=20, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.PModel', verbose_name='型號'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=3999, verbose_name='價格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.PositiveIntegerField(default=0, verbose_name='使用幾年'),
        ),
    ]
