# Generated by Django 3.0.2 on 2021-08-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_table',
            name='car_maker',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
